### ISSUE TITLE
Erorr main.py

### ISSUE THREAD

**Issue by gemblung2019** [bro-11/fasterbot#8]
testing setelah update, main.py ada eror saat memilih pembayaran via bank

Traceback (most recent call last):
  File "/root/fasterbot/main.py", line 90, in <module>
    options = dict(enumerate(selected_payment_channel.options().keys()))
TypeError: 'dict' object is not callable

**Comment by gemblung2019** [comment]
saya pakai python 3.9.5 apakah pengaruh

**Comment by bro-11** [comment]
oh iya bang makasih sarannya, kemaren ane otak atik dikit, lupa ada yg belum diubah

**Comment by gemblung2019** [comment]
saya hanya pengguna yg berharap dapat hoki pake tool ini 😀
